version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
  app:
    image: ahiipsa/shorts-reels-videos.backend:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env



